### PR TITLE
Added built-in rain effect and bug fixes. See change log.

### PR DESCRIPTION
**Pull request by moose4lord**

### CODE REVIEW

**Comment by TysTiesINC** [comment]
how can I edit the library an add more built-in effects?

**Comment by moose4lord** [comment]
Do you want to create your own effects? Or are you trying to get more of the built-in effects to work on an Arduino?

**Comment by TysTiesINC** [comment]
I want to find other effects people have created and put them in. 
such as the effects in this project: https://github.com/modustrialmaker/Lightsaber_single_blade_neopixel

**Comment by moose4lord** [comment]
I see. [FastLED](https://fastled.io/) is a popular library to create custom effects (including the light saber project you mentioned). Unfortunately, WS2812FX and FastLED are not that compatible. The two libraries use  different code bases to drive the LED strip, so getting them to work together is a pain. The ws2812fx_custom_FastLED example sketch shows how to combine the two libraries, but it's really just a hack. You need to copy the FastLED code to run the animation, then inject code at the end to copy the FastLED data to the WS282FX instance. It's very messy.

If you have an ESP32 or ESP8266 processor, you might want to look at the [WLED](https://kno.wled.ge/) project. It has all the WS2812FX effects, plus adds many interesting FastLED effects.

**Comment by TysTiesINC** [comment]
Ok. Thanks for your time. Does the WLED have a github page?

**Comment by TysTiesINC** [comment]
Ok. Thanks for your time. Does the WLED have a github page?

**Comment by dsssssssss9** [comment]
Yes it does....

https://github.com/Aircoookie/WLED

Also a Discord Server....
https://discord.gg/wAjbbPSh

**Comment by moose4lord** [comment]
If you can find NeoPixel effects, they should work with the WS2812FX library. But I don't think you'll find many. I think most people that want to create new effects use FastLED.

**Comment by TysTiesINC** [comment]
Ok. I've been looking into WLED. Is there a way to just use their version of WS2812FX like you would use the normal one?

**Comment by moose4lord** [comment]
I looked at the WLED code and it's using an old, heavily modified version of WS2812FX under the covers. The inner workings of the WLED code is quite different from the WS2812FX code. I tried to get one of the extra WLED effects to compile with WS2812FX, but got many errors.

The WLED effects could probably be made compatible with WS2812FX, but it would take a considerable effort.

**Comment by TysTiesINC** [comment]
ok. thanks for your time.

**Pull request merged**
