### PR TITLE
Add ON / OFF / PAUSE / RESUME to webinterface 

### PR DESCRIPTION
**Pull request by Kaibob2**
I added a Play / Pause and ON / OFF Button to the webinterface.
Borrowed code from FloEdelmann from #118
This PR enables to switch the LEDs on or off completely (reset runtime) from the webinterface ans also only Pause or resume the effect (via #118 )
I'm not sure if the way i implemented it is the best and shortest way to do it, but it works great and is essential for my usage scenario.

### CODE REVIEW

**Comment by Kaibob2** [comment]
screenshot

This is what it looks like

**Comment by FloEdelmann** [comment]
@Kaibob2 PR #118 is merged, you'll now have to resolve the merge conflict (i.e. add the missing empty line between `pause()` and `resume()`) so that @kitesurfer1404 or @moose4lord can merge this PR seamlessly.

**Comment by Kaibob2** [comment]
@FloEdelmann Sometimes Github is still a mystery to me, but i think it will be mergeable now :)

**Comment by Kaibob2** [comment]
Thanks for merging.

**Pull request merged**
